spring:
  application:
    name: "main-service"

  config:
    import:
      - optional:file:.env[.properties]
      - classpath:application-db.yml
      - classpath:application-mb.yml
      - classpath:application-redis.yml
      - classpath:application-swagger.yml

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-validity: ${JWT_ACCESS_TIME}
  refresh-token-validity: ${JWT_REFRESH_TIME}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springdoc: DEBUG
    io.swagger.v3: DEBUG

minio:
  endpoint: ${MINIO_URL}
  access-key: ${MINIO_USERNAME}
  secret-key: ${MINIO_PASSWORD}
