version: "3.8"

services:
  # --- Logstash ---
  logstash:
    image: logstash:7.17.0
    container_name: logstash
    volumes:
      - ../logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./logs/application.log:/app/logs/application.log
    ports:
      - "5000:5000"
    networks:
      - logging-network
    depends_on:
      - elasticsearch

  # --- Elasticsearch ---
  elasticsearch:
    image: elasticsearch:8.8.0
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
      xpack.security.enrollment.enabled: "true"
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    networks:
      - logging-network

  # --- Kibana ---
  kibana:
    image: kibana:8.8.0
    container_name: kibana
    environment:
      - 'ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]'
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - logging-network

networks:
  logging-network:
    driver: bridge
