version: "2.1"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:56723"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RMQ_PWD:-guest}
