version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: vet_clinic_db
    environment:
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_PASSWORD: ${PG_PWD:-postgres}
      POSTGRES_DB: ${PG_DB:-clinic}
    ports:
      - "5432:5432"
    volumes:
      - ../pgdata:/var/lib/postgresql/data

  # --- pgAdmin ---
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
