global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'main-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['main-service:8080']

  - job_name: 'email-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'email-service:8081' ]

  - job_name: 'minio'
    metrics_path: '/minio/prometheus/metrics'
    static_configs:
      - targets: ['minio:9000']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']

  - job_name: 'postgres'
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]

  - job_name: 'redis'
    static_configs:
      - targets: [ 'redis-exporter:9121' ]