version: "3.8"

services:
  postgres:
    image: postgis/postgis:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - ./pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:6.21
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8888:80"
    depends_on:
      - postgres

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RMQ_PWD}
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq_definitions.json:/etc/rabbitmq/rabbitmq_definitions.json

  main-service:
    build:
      context: ../../main-service
      dockerfile: Dockerfile
    env_file:
      - ../../.env
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_started
    ports:
      - "8080:8080"

  email-service:
    build:
      context: ../../email-service
      dockerfile: Dockerfile
    env_file:
      - ../../.env
    depends_on:
      rabbitmq:
        condition: service_started
    ports:
      - "8081:8081"

networks:
  logging-network:
    driver: bridge