services:
  # --- Postgres ---
  postgres:
    image: postgres:latest
    container_name: vet_clinic_db
    environment:
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_PASSWORD: ${PG_PWD:-postgres}
      POSTGRES_DB: ${PG_DB:-vet_clinic}
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  # --- pgAdmin ---
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    networks:
      - app-network

  # --- RabbitMQ ---
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:56723"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RMQ_PWD:-guest}

  # --- Redis ---
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - app-network

  # --- Logstash ---
  logstash:
    image: logstash:7.17.0
    container_name: logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./logs/application.log:/app/logs/application.log
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - elasticsearch

  # --- Elasticsearch ---
  elasticsearch:
    image: elasticsearch:8.8.0
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
      xpack.security.enrollment.enabled: "true"
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    networks:
      - app-network

  # --- Kibana ---
  kibana:
    image: kibana:8.8.0
    container_name: kibana
    environment:
      - 'ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]'
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
